name: Build site on 5 AM - midnight on every hour

on:
  push:
    branches:
      - master

  schedule:
    - cron: "55 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: joelwmale/webhook-action@master
        with:
          # set this to Netlify build webhook URL
          # https://docs.netlify.com/configure-builds/build-hooks/
          url: ${{ secrets.NETLIFY_BUILD_WEBHOOK_URL }}
